mqtt:
  topic-name: plc4x/test-topic
  server-host: test.mosquitto.org
  server-port: 1883
plc:
  connection: simulated:plc4x-example-mqtt
  addresses:
    - name: intParam
      address: RANDOM/foo:INTEGER
      size: 1
      type: java.lang.Integer
    - name: intParam2
      address: RANDOM/bar:INTEGER
      size: 1
      type: java.lang.Integer
polling-interval: 2000
