mqtt:
  topic-name: plc4x/modbus-test
  server-host: test.mosquitto.org
  server-port: 1883
plc:
  connection: modbus:tcp://127.0.0.1:502
  addresses:
    - name: 400002
      address: 400002
      size: 1
      type: java.lang.Integer
    - name: 400003
      address: 400003
      size: 1
      type: java.lang.Integer
polling-interval: 2000