version: "3.9"
services:

  dev-grafana:
        image: grafana/grafana
        restart: always
        ports:
          - "8080:3000"
        depends_on:
          - influxdb
        volumes:
          - grafana-storage:/var/lib/grafana
        build:
          context: ./grafana
    
  hivemq:
    image: hivemq/hivemq-ce
    restart: always
    ports:
      - "1883:1883"
    networks:
      - industrial-data-extraction-network

  data-extractor:
    build: industrialdataextraction
    platform: linux/amd64
    restart: always
    ports:
      - "8081:1883"
    depends_on:
      - hivemq
      - modbus-server
    networks:
      - industrial-data-extraction-network
           
  modbus-server:
    build: modbus-server
    ports:
      - 502:502
    restart: on-failure
    networks:
      - industrial-data-extraction-network
    volumes:
      - extractor-storage:/var/lib/extractor

  modbus-client:
    build: modbus-client
    restart: on-failure
    depends_on:
      - modbus-server
    networks:
      - industrial-data-extraction-network  

networks:
  industrial-data-extraction-network:

volumes:
 influxdb-storage:
 grafana-storage:
 extractor-storage:
